### ISSUE TITLE
relative path doesn't work with dune 3.0

### ISSUE THREAD

**Issue by dhcmrlchtdj** [johnwhitington/ppx_blob#23]
If we change `(lang dune 1.0)` to `(lang dune 3.0)` (https://github.com/johnwhitington/ppx_blob/blob/0.7.2/dune-project#L1
the build will failed with following error.
```
$ make all
dune build @install @example
File "example/quine.ml", line 1, characters 13-31:
1 | print_string [%blob "quine.ml"]
                 ^^^^^^^^^^^^^^^^^^
Error: [%blob] could not find or load file quine.ml
```

I found that [`Ocaml_common.Location.absolute_path path`](https://github.com/johnwhitington/ppx_blob/blob/0.7.2/src/ppx_blob.ml#L9) no longer return a real path but prefix the argument with `/workspace_root/`.
Since there is no `/workspace_root/example/quine.ml`, a `Not_found` is thrown.

**Comment by johnwhitington** [comment]
So dune is overwriting `Ocaml_common.Location.absolute_path` in some way in order to sandbox build artefacts? What is the mechanism here?

Maybe we just need to tell dune to copy `quine.ml` into the workspace, since it is not just a source file, but also a file the compilation process reads from?

If that's not the case, we should add a comment in the example program to explain that this behaviour is dune-specific. Dune may be the most widely used build system, but it isn't part of OCaml.

**Comment by superherointj** [comment]
I'm struggling with this problem. My dune knowledge is somewhat limited. I couldn't find the right solution to make it work.

Errors like this:
`
       > 3 |   let token = [%blob "bot.token"]
       >                   ^^^^^^^^^^^^^^^^^^^
       > Error: [%blob] could not find or load file bot.token
`
File is at same folder *.ml/dune file is. But doesn't work.

Any suggestion? Thanks.

**Comment by rgrinberg** [comment]
Note that `/workspace_root` is in fact inserted by the compiler. Dune just sets `BUILD_PATH_PREFIX_MAP` appropriately to ask ocamlc to produce reproducible artifacts.

> Maybe we just need to tell dune to copy quine.ml into the workspace, since it is not just a source file, but also a file the compilation process reads from?

Yes indeed. You should do that. We have a `preprocessor_deps` field in dune for exactly this purpose.
